config/routes.rb
Rails.application.routes.draw do
  get 'users/:id', to: 'users#show', as: 'user'

  resources :reservations
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
	get "signin", to: 'devise/sessions#new'
	delete "signout", to: 'devise/sessions#destroy'
	get "signup", to: 'devise/registrations#new'
  end
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'contacts', to: 'pages#contacts'
  get 'learn', to: 'pages#learn'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
# app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
	user && user.admin?
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user

  def start_time
     self.slot
  end
  def name
    self.eventname
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def access_denied(exception)
	redirect_to root_path, alert: exception.message
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /reservations
  def index
    @reservations = Reservation.order(:slot).all
  end

  # GET /reservations/1
  def show
    @reservation = Reservation.find(params[:id])
  end

  # GET /reservations/new
  def new
    @reservation = current_user.reservations.new
    @reservation.slotdate = params[:slotdate]
  end

  # GET /reservations/1/edit
  def edit
    @reservation = current_user.reservations.find(params[:id])
  end

  # POST /reservations
  def create
    @reservation = current_user.reservations.new(reservation_params)
    @reservation.slot = DateTime.parse(@reservation.slotdate.to_s + " " + @reservation.slothour.to_s + ":00:00")

   begin
    if @reservation.save
      redirect_to @reservation, notice: 'Reservation was successfully created.'
    else
      render :new 
    end
   rescue 
       flash[:error] = "That time slot is already taken."
      render :new
   end
  end

  # PATCH/PUT /reservations/1
  def update
    @reservation = current_user.reservations.find(params[:id])
    begin
    if @reservation.update(reservation_params)
      @reservation.slot = DateTime.parse(@reservation.slotdate.to_s + " " + @reservation.slothour.to_s + ":00:00")
      if @reservation.save
         redirect_to @reservation, notice: 'Reservation was successfully updated.' 
      end
    else
      render :edit 
    end
    rescue
	flash[:error] = "That time slot is already taken."
	render :edit
    end
  end

  # DELETE /reservations/1
  def destroy
    @reservation = current_user.reservations.find(params[:id])
    @reservation.destroy
      redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' 
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:slotdate, :slothour, :eventname, :eventtype)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Month Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-dark bg-inverse">
      <div class="container">
        <%= link_to "Alderman Library Reservations", root_path, class: "navbar-brand" %>
        <ul class="nav navbar-nav">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", contacts_path, class: "nav-link" %></li>
	  <% if user_signed_in? %>
	  	<% if current_user.admin %>
          		<li class="nav-item float-md-right"><%= link_to "Admin", admin_root_path, class: "nav-link" %></li>
	  	<% end%>
          <li class="nav-item float-md-right"><%= link_to "Log out", signout_path, method: :delete, class: "nav-link" %></li>
	  <% else %>
          <li class="nav-item float-md-right"><%= link_to "Log in", signin_path,  class: "nav-link" %></li>
          <li class="nav-item float-md-right"><%= link_to "Create account", signup_path,  class: "btn btn-primary" %></li>
	  <% end %>
        </ul>
      </div>
    </nav>
 
    <!--  Flash Messages -->
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
    <% end %>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 One Month</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>The U.Va. Library’s primary mission is to serve University of Virginia students, faculty, and staff, as well as researchers and alumni. Rooms throughout our libraries can be reserved by faculty, staff, and students affiliated with the University of Virginia for group study, meetings, occasional teaching and presentations.</p>
    </div>
</div>

app/views/pages/contacts.html.erb
<div class="container">
<h1>Contact Us</h1>
<ul>Library Room Reservation Staff Members</ul>
<li><a href="mailto:sandy@virginia.edu">Sandy Bryant</a></li>
<li><a href="mailto:sh@omr.org">Susie Helpful</a></li>
<li><a href="mailto:fb@omr.org">Fred Boss</a></li>
<li><a href="mailto:nc@omr.org">Nancy Coder</a></li>
</ul>
</div>

app/views/pages/home.html.erb
<div class="jumbotron jumbotron-home">
    <div class="container">
	<% if user_signed_in? %>
		<h1>Welcome back, 
		<%= current_user.email %>
		</h1>
        	<%= link_to "View Reservations »", reservations_path, class: "btn btn-primary btn-lg" %> 
	<% else %>
        	<h1>Alderman Library McGregor Room</h1>
        	<p>If Harry Potter had a favorite study place this would be it. Very quiet … often a little dark. A charming favorite. The McGregor Room can now be reserved by libary patrons for special events.</p>
        	<%= link_to "View Reservations »", reservations_path, class: "btn btn-primary btn-lg" %> 
	<% end %>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Study Groups</h2>
            <p>Have a big group project due? Use the McGregor Room as your meeting spot. Available during normal Alderman operating hours to any University student with an active library account.<p>
            <% if user_signed_in?  %>
		<% if current_user.classification == 'student' %>
              		<p><%= link_to "Reserve", new_reservation_path, class: "btn btn-secondary" %></p>
            	<% else %>
              		<p><%= link_to "Learn More", learn_path, class: "btn btn-secondary" %></p>
		<% end %>
	    <% else %>
              	<p><%= link_to "Log in to Reserve", signin_path, class: "btn btn-secondary" %></p>
            <% end %>
        </div>
        <div class="col-md-4">
            <h2>Faculty Parties</h2>
            <p>The McGregor Room can be reserved for department functions.  Acess and facilities for catering provided in adjacent kitchen.</p>
            <% if user_signed_in?  %>
		<% if current_user.classification == 'faculty' %>
              		<p><%= link_to "Reserve", new_reservation_path, class: "btn btn-secondary" %></p>
            	<% else %>
              		<p><%= link_to "Learn More", learn_path, class: "btn btn-secondary" %></p>
		<% end %>
	    <% else %>
              	<p><%= link_to "Log in to Reserve", signin_path, class: "btn btn-secondary" %></p>
            <% end %>
        </div>
        <div class="col-md-4">
            <h2>Alumni Tours</h2>
            <p>The McGregor Room is available for special events during Reunion Weekends to alums</p>
            <% if user_signed_in?  %>
		<% if current_user.classification == 'alum' %>
              		<p><%= link_to "Reserve", new_reservation_path, class: "btn btn-secondary" %></p>
            	<% else %>
              		<p><%= link_to "Learn More", learn_path, class: "btn btn-secondary" %></p>
		<% end %>
	    <% else %>
              	<p><%= link_to "Log in to Reserve", signin_path, class: "btn btn-secondary" %></p>
            <% end %>
        </div>
    </div>
</div>

app/views/pages/learn.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Reservation Policies Explanation</h1>
	<% if user_signed_in? %>
		<p>We think <%=current_user.email%> has classification =><%=current_user.classification %><=</p>
	<% else %>
		<p>Since you are not logged in, we can't assign your classification.</p>
	<% end %>
        <p>Here would go text explaining how to get your proper user account classification  allocated (normally, we'd be using single signon and then authorizing an account with a LDAP lookup).</p>
	<p>Here would go text explaining which categories of reservations each classification can make.</p>
    </div>
</div>

app/views/reservations/_form.html.erb
<%= form_for(reservation) do |f| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label  :slotdate, "Date" %>
    <% if (reservation.user.classification == 'alum') || (reservation.user.classification == nil) %>
    	<%= f.select :slotdate, [['Friday January 4','2017-01-04'],['Saturday January 5','2017-01-05'],['Sunday January 6, 2017','2017-01-06']],class: "custom-select" %>
    <% else %>
    	<%= f.date_select :slotdate , class: "form-control"%>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :slothour , "Hour"%>
    <% if reservation.user.classification == 'student' %>
    	<%= f.select :slothour , [['8am',8],['9am',9],['10am',10],['11am',11],['noon',12],['1pm',13],['2pm',14],['3pm',15],['4pm',16],['5pm',17],['6pm',18],['7pm',19],['8pm',20],['9pm',21],['10pm',22]], class: "custom-select" %>
    <% else %>
    	<%= f.select :slothour , [['midnight',0],['1 am',1],['2am',2],['3am',3],['4am',4],['5am',5],['6am',6],['7am',7],['8am',8],['9am',9],['10am',10],['11am',11],['noon',12],['1pm',13],['2pm',14],['3pm',15],['4pm',16],['5pm',17],['6pm',18],['7pm',19],['8pm',20],['9pm',21],['10pm',22],['11pm',23]], class: "custom-select" %>
    <% end %>

  </div>
  <div class="form-group">
    <%= f.label :eventname , "Event Name"%>
    <%= f.text_field :eventname , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :eventtype, "Event Type"%>
    <% if reservation.user.classification == 'student' %>
    	<%= f.select :eventtype, [["Study Group","s"]],class: "custom-select" %>
    <% else %>
	<% if reservation.user.classification == 'alum' %>
    		<%= f.select :eventtype, [["Alumni Tour","a"]],class: "custom-select" %>
	<% else %>
		<% if reservation.user.classification == 'faculty' %>
    			<%= f.select :eventtype, [["Study Group","s"],["Faculty Function","f"],["Alumni Tour","a"]],class: "custom-select" %>
		<% else %>
    			<%= f.select :eventtype, [["Alumni Tour","a"]],class: "custom-select" %>
		<% end %>
	<% end %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<div class="container">
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>
</div>

app/views/reservations/index.html.erb
<div class="container">

  <h1>Reservations</h1>
  

<%= month_calendar  events: @reservations do  |date, meetings| %>
  <% if user_signed_in? && date.future? %>
    <%= link_to date.strftime("%m/%d"), new_reservation_path(:slotdate => date.to_s)  %>
  <% else %>
    <%= date.strftime("%m/%d") %>
  <% end %>

  <% meetings.each do |meeting| %>
    <div>
      <%= meeting.slot.strftime("%l:%M %p") %></br>
      (<%= link_to meeting.name, meeting %>)
    </div>
  <% end %>
<% end %>
  
  <br>
  
  <% if user_signed_in? %>
    <%= link_to 'New Reservation', new_reservation_path %>
  <% end %>
</div>

app/views/reservations/new.html.erb
<div class="container">
  <h1>New Reservation</h1>

  <%= render 'form', reservation: @reservation %>

  <%= link_to 'Back', reservations_path %>
</div>

app/views/reservations/show.html.erb
<div class="container">
<h1>Reservation</h1>
<p>
  <strong>Owner:</strong>
  <%= link_to @reservation.user.email, user_path(@reservation.user.id) %>
</p>

<p>
  <strong>Date:</strong>
  <%= @reservation.slot.strftime("%Y-%m-%-d") %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @reservation.slot.strftime("l:%M %p") %>
</p>

<p>
  <strong>Event:</strong>
  <%= @reservation.eventname %>
</p>

<% if @reservation.user == current_user %>
<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<% end %>
<%= link_to 'Back', reservations_path %>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="container">
<h1>User Profile</h1>
<p><%= mail_to @user.email, @user.email %></p>
<p>Classification: <%=@user.classification ||= 'none'%></p>
<%= link_to "Back", reservations_path %>
</div>